version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sfcc-api
    container_name: sfcc-api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 5000:80
    env_file:
      - .env

  queue:
    image: sfcc-api
    container_name: sfcc-queue
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - CONTAINER_ROLE=queue
    env_file:
      - .env
    depends_on:
      - api

  redis:
    image: redis:alpine
    container_name: sfcc-redis
